/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Question =
  | {
      answer: Answer;
      type: "FreeInput";
      [k: string]: unknown;
    }
  | {
      answers: Answer[];
      type: "SingleChoice";
      [k: string]: unknown;
    }
  | {
      answers: Answer[];
      type: "MultiChoice";
      [k: string]: unknown;
    }
  | {
      categories: Category[];
      type: "Categorize";
      [k: string]: unknown;
    };

export interface Quiz {
  frontmatter?: unknown;
  items: Section[];
  [k: string]: unknown;
}
export interface Section {
  header: string;
  items: Section[];
  metadata?: unknown;
  question?: Question | null;
  text?: string | null;
  [k: string]: unknown;
}
export interface Answer {
  correct: boolean;
  label?: string | null;
  notes?: string | null;
  text: string;
  [k: string]: unknown;
}
export interface Category {
  answers: Answer[];
  text: string;
  [k: string]: unknown;
}
